version: '3.5'

services:
    app:
        image: node:12-alpine
        volumes:
            - ./:/app
        working_dir: /app
        ports:
            - 9090:9090
        command: npm start
        tty: true